name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "phamminhthinh9x@gmail.com"
        git config --global user.name "thinhpm"

    - name: Authenticate with Hugging Face
      env:
        HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
      run: |
        git remote set-url origin https://thinhpm:${{ secrets.HUGGINGFACE_TOKEN }}@huggingface.co/spaces/thinhpm/tele-be
        git config --global credential.helper store
        echo "https://${{ secrets.HUGGINGFACE_TOKEN }}:@huggingface.co" > ~/.git-credentials
        
    - name: Check the current branch
      run: |
        git branch
        git status
        
    - name: Push to Hugging Face
      run: |
        git push origin
